# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: cfers's Blog
subtitle: code better life ;)
author: Chen Fei 
language: english
timezone: utc+8

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://cfers.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: cfers的博客 | cfers's Blog
header-img: img/home-bg.jpg
email: cfersx@gmail.com
description: "cfers技术分享"
keyword: "技术分享 cfers"


# SNS settings
# RSS: false
weibo_username:     topcoder_cfers
zhihu_username:     cfers
github_username:    cfers
twitter_username:   cfersX
facebook_username:  cfersX
linkedin_username:  cfersX

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username: cfers

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: cfers.vip


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "better, step by step!"
sidebar-avatar: /img/me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
friends: [
    {
        title: "cfers's Blog",
        href: "http://cfers.vip"
    }
]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: i_dont_wanna_use_default_archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/cfers-pub/blog
  branch: master
